### ISSUE TITLE
Write non-normative description to cover private key sensitivity

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-dcp/decentralized-claims-protocol#10]
For @borisrizov-zf

Insert non-normative text covering private key sensitivity.

**Comment by jimmarino** [comment]
Not critical for first release.

**Comment by borisrizov-zf** [comment]
Hi, sorry I've been rushing to get some fixes done elsewhere. I have the documents open, but not ready for a PR yet.
