### ISSUE TITLE
Rename credential offers to notifications and define proof-of-possesion methodolgy

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-dcp/decentralized-claims-protocol#11]
For @borisrizov-zf

We decided to rename credential offers to `credential notifications` and include a proof-of-posession feature for sending notifications.

**Comment by borisrizov-zf** [comment]
@jimmarino There seems to be a double key entry `credentials` in section 4.1.1 can you take a look and advise. Also the sentence in the first occurrence is incomplete, should I just consolidate them?

**Comment by jimmarino** [comment]
I think that is a merge error. Can you clean that up as part of this PR?

**Comment by borisrizov-zf** [comment]
@jimmarino one more thing, do you remember what we decided for the keys in json? camelCase or snake_case?

**Comment by jimmarino** [comment]
> @jimmarino one more thing, do you remember what we decided for the keys in json? camelCase or snake_case?

I can't remember exactly but DSP uses camel case and since we are planning on contributing these specs there at some point, it may make sense to adopt that convention.

**Comment by borisrizov-zf** [comment]
> > @jimmarino one more thing, do you remember what we decided for the keys in json? camelCase or snake_case?
> 
> I can't remember exactly but DSP uses camel case and since we are planning on contributing these specs there at some point, it may make sense to adopt that convention.

Ok, I'll do that then. Maybe we should have a quick chat, because I've got some other questions, are you on matrix?
