### ISSUE TITLE
Profile definitions for DCP

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspace-dcp/decentralized-claims-protocol#118]
### What's missing?

DCP should specify profiles that clearly define the VC data model, the credential revocation mechanism and the cryptographic proof stack.

### Why should it be in the spec?

to achieve interoperability. Without specifying these profiles, it is virtually impossible for two DCP communication partners to ever be interoperable, due to the sheer complexity of the involved mechanisms.

### More context

The proposed matrix is as follows

- Variant 1: VC DataModel 1.1 + StatusList2021 + EmbeddedProofs (JsonWebSignature2020)
- Variant 2: VC DataModel 1.1 + StatusList2021 + External Proofs (JWT)
- Variant 3: VC DataModel 2.0 + BitStringStatusList + EmbeddedProofs (only `DataIntegrityProofs` of type `eddsa-jcs-2022`, `proofPurpose` must be `assertionMethod`)
- Variant 4: VC DataModel 2.0 + BitStringStatusList + JWT proofs, no JWE support
- Variant 5: VC DataModel 2.0 + BitStringStatusList + SD-JWT
- Variant 6: VC DataModel 2.0 + BitStringStatusList + CBOR (not sure how widely spread that really is)

(edit: changed from `eddsa-rdfc-2022` to `eddsa-jcs-2022`)

Whether this actually translates into six _profiles_, or two _main profiles_ with "sub-profiles"  should be discussed further. 

Main profiles could be:
- "vc1.1+sl2021" with "ldp-vc" and "jwt-vc" as sub-profiles
- "vc2.0+bssl" with "jwt", "sd-jwt" and "cbor" as sub-profiles
- "vc2.0+bssl" with "eddsa-jcs-2022` as sub-profile (implies embedded proof)

**Comment by arnoweiss** [comment]
i think this is a great idea. Should this also include the signature algorithm?

**Comment by paullatzelsperger** [comment]
> i think this is a great idea. Should this also include the signature algorithm?

we could, but if i'm honest I would expect most implementors to be able to handle a variety of cryptographic primitives anyway; whether something is signed with an EC key or an EdDSA key should not matter much in practice.

**Comment by arnoweiss** [comment]
Especially if this is supposed to determine what's supposed to go into the [`CredentialObject`](https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/#credentialobject)'s `cryptography` property, I think listing signature algos would make sense - or we should change the property's textual definition. 

Another place that might be on the receiving end of this exercise is the `format` property.

**Comment by paullatzelsperger** [comment]
in some constellations there is an implicit restriction, for example "external proofs" in VC 2.0, when secured with the `eddsa-jcs-2022` suite, only allow proofs to be created using the Ed25519 curve. 

Others, like "enveloped proofs" using JWT don't impose such restrictions. Consequently, issuers are allowed to sign the credentials with all sorts of EC keys, RSA, EdDSA,... and the specific type would be communicated in the JWT's `alg` header. 

To my understanding, the `cryptography` object would then contain the "variant", so for example `vc2.0+bssl/jwt`, which would mean "use VC 2.0, BitStringStatuslist and enveloped proofs with JWT". Another would be `vc2.0+bssl/eddsa-jcs-2022`, which implies the use of embedded proof using the `eddsa-jcs-2022` suite.

**Comment by paullatzelsperger** [comment]
In an offline meeting, @hkny and @arnoweiss and I agreed on the following items:
- DCP will define 2 profiles as sane defaults. Each profile has a unique alias
  - VC2.0 + BitStringStatusList + JWT proofs, alias `vc20+bssl/jwt`
  - VC1.1 + StatusList2021 + JWT proofs, alias `vc10+sl2021/jwt`

- those profile definitions will initially be hosted in the DCP repository, with the option to move them out later if needed
- for issuance, the “cryptography” object will contain the profile alias
- for presentation, the “format” property will contain the profile alias
- additional profiles can be defined by data spaces, possibly based upon those mentioned above with additional restrictions
- the DCP specification document should contain non-normative text to indicate to profile authors what their profile should define (VC datamodel, revocation system, proof mechanism, etc.)
