### ISSUE TITLE
Pinned/Versioned ReSpec deployments

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspace-dcp/decentralized-claims-protocol#123]
### What's missing?

For pinned versions of the DSP spec, there should be corresponding ReSpec deployments. So as a reader of the spec I have a way to look up version 1.0, 2.0 etc. of the specification document.

### Why should it be in the spec?

For public releases of the spec there should be the corresponding immutable specification document.

### Where should this be added?

one way to do it would be to encode the version into the GitHub pages URL: 
- https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/latest points to the _latest published version_, i.e. whatever is published directly off of `main`
- https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/0.1.2 would point to a the respective (possibly outdated) release version `v0.1.2` of the spec 
- https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/ always points to the _last stable release_. Note that that version would also be available at its release path, e.g. `/decentralized-claims-protocol/0.8.0`.

This should be doable using subfolders in GH Pages.

### More context

[edit]: actually, we may want a dedicated GH Actions workflow to automatically create a tag, create a GH Release and publish the ReSpec at a dedicated URL

**Comment by arnoweiss** [comment]
I was thinking something similar. 
1. Scrape all tags, 
2. checkout main for the tag
3. build respec
4. dump in github-pages subfolders

As the 0.8 release only contains md-files, this wouldn't be of much use. For the upcoming `editor's draft` and `latest` however, we'd have two separate webpages.

**Comment by arnoweiss** [comment]
On Release, there must be 
- a commit that:
  - sets a new tag
  - sets the `specStatus` config option to `base`
  - sets the title of the spec to "Eclipse Decentralized Claims Protocol v1.0.0-RC01"
- new redirects configured in `perma-id/w3id` if necessary
- edit top-level `index.html` that redirects to the latest stable version

After Release
- reset `specStatus` config option to `unofficial`
- reset the title of the spec to "Eclipse Decentralized Claims Protocol v1.0.0"
