### ISSUE TITLE
Rework 4.1. Self-Issued ID Token Contents

### ISSUE THREAD

**Issue by matgnt** [eclipse-dataspace-dcp/decentralized-claims-protocol#26]
I think we need to clarify some part in this section
https://github.com/eclipse-tractusx/identity-trust/blob/8215853dddad222b1cdb81d2d16d202265ea698a/specifications/M1/identity.protocol.base.md?plain=1#L67C3-L67C37

> - The `iss` and `sub` claims MUST be equal and set to the bearer's (participant's) DID.

First part is clear. Who is the bearer? Participant also doesn't help because 2 participants are involved.

> - The `aud` set to the `participant_id` of the relying party (RP)

who is the relying party? VC fetching perspective or original DSP call, e.g. catalog request?

> - All VPs in the `vp` claim MUST be in the format specified by

What is this used for? It is part of the MUST section. Later we describe we transfer access tokens inside the SI token.

Could you have a look please, @jimmarino

**Comment by jimmarino** [comment]
Use, this is related to #27

**Comment by jimmarino** [comment]
> I think we need to clarify some part in this section https://github.com/eclipse-tractusx/identity-trust/blob/8215853dddad222b1cdb81d2d16d202265ea698a/specifications/M1/identity.protocol.base.md?plain=1#L67C3-L67C37
> 
> > * The `iss` and `sub` claims MUST be equal and set to the bearer's (participant's) DID.
> 
> First part is clear. Who is the bearer? Participant also doesn't help because 2 participants are involved.

I think this is clear, it's the bearer of the token. In some implementations, this may not be the same as the client making the request to the STS. The bearer will be the client that uses the token to request a protected resource, e.g. a catalog, contract negotiation, etc. However, that is not necessarily a `connector`.

The important point is that the `iss` and `sub` claims specify the identity of whatever client is converting (bearing) the token.

> 
> > * The `aud` set to the `participant_id` of the relying party (RP)
> 
> who is the relying party? VC fetching perspective or original DSP call, e.g. catalog request?

Let's not confuse those. The relying party, in this case, is the entity that is determining whether to grant access to a protected resource, e.g., the catalog. The protected resource, in this case, is *not* a set of `VCs`.
