### ISSUE TITLE
Remove the unused `vp` claim and reference OAuth 2.0 endpoint parameters.

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-dcp/decentralized-claims-protocol#27]
We need to perform minor cleanup to remove the old `VP` claim text in the base protocol document and add a reference to OAuth 2 endpoint parameters. 

Since these changes are minor and in the same document, they will be done in one PR.

**Comment by matgnt** [comment]
Realted to #26 the question with `VP`
