### ISSUE TITLE
patchwork of different standards

### ISSUE THREAD

**Issue by Sakurann** [eclipse-dataspace-dcp/decentralized-claims-protocol#34]
flows defined in this repository use artifacts defined in other specifications in the context different from what is intended in original specifications, and that is confusing and feels like a patchwork using components from different standards.

From what I can tell...

1. Self-Issued ID token is used not as defined by SIOPv2 specification. Only Self-Issued ID Token syntax is used partially.
2. Only OpenID4VP response is used and not really the request.
3. It looks like the intent is to use Access token as defined in OAuth 2.0 (rfc6749), but which grant type is used to issue these access tokens..? please either define a new grant type (which I am not sure is possible, because there is no request from the verifier who is an ultimately using that AT) or stop calling these artifacts access tokens.

points 1 and 2 lead to security concerns like raised in this issue #33 

In general, there is a pattern that artifacts/tokens are issued without a request from an entity that the artifact is sent to, which is very different from the standards being quoted and would require a thorough security analysis.

**Comment by Sakurann** [comment]
for access token, a new grant type should probably be defined like in https://www.rfc-editor.org/rfc/rfc7523, but where JWT is not bearer. maybe something like `urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation` defined in https://datatracker.ietf.org/doc/html/[draft-ietf-oauth-attestation-based-client-auth-01 (I filed an issue)

**Comment by borisuu** [comment]
@paullatzelsperger @jimmarino I think @Sakurann has some valid points, at least we should try to consolidate the wording in the docs and the diagrams.

**Comment by borisrizov-zf** [comment]
@paullatzelsperger @jimmarino I think @Sakurann has valid points, we should do another round of updates to consolidate the wording and definitions. I've noticed that sometimes the tokens are called SI token, sometimes JWT ID tokens, etc. Let's use the opportunity to discuss. What do you guys think?

**Comment by jimmarino** [comment]
> @paullatzelsperger @jimmarino I think @Sakurann has valid points, we should do another round of updates to consolidate the wording and definitions. I've noticed that sometimes the tokens are called SI token, sometimes JWT ID tokens, etc. Let's use the opportunity to discuss. What do you guys think?

+1 for having a standard nomenclature and cleaning up inconsistencies. I'll address the larger issues raised here and in #33 once I have time to respond. To summarize:

- It is OK to reference parts of other specifications when appropriate, as long as it is done concisely and consistently.  

- The world an asynchronous, reliable messaging protocol such as DSP introduces comes with very different requirements, assumptions, and constraints than a user-oriented protocol. Another way of looking at this is: Asynchrony is that start and end point, and trust interactions must adapt to it, not the other way around.

I'll write a more detailed response as soon as I have time.

**Comment by Sakurann** [comment]
How was this addressed? Why does this get silently closed?
