### ISSUE TITLE
Publish IATP Json-Ld Context

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-dcp/decentralized-claims-protocol#35]
Originally brought up in #32, when we create a static publication of the IATP documents, we need to publish the Json-Ld context using the following URL with a redirect:

`https://w3id.org/tractusx-trust/v0.8`

This is not critical, as implementations should reference the context from a trusted cache.

**Comment by arnoweiss** [comment]
URI changed to https://w3id.org/dspace-dcp/v0.8, see https://github.com/perma-id/w3id.org/pull/4539

@wolf4ood - can you close this?
