### ISSUE TITLE
determine correct ref to oauth2 spec

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-dcp/decentralized-claims-protocol#58]
https://github.com/eclipse-tractusx/identity-trust/blob/a14a6c358beee1b5f63f508d0b545869ba2521d9/specifications/verifiable.presentation.protocol.md?plain=1#L251

**Comment by nikschul** [comment]
Hi @jimmarino,
is it section 4.4 of the OAuth2 specification or a respective subsection that you wanted to mention here? https://datatracker.ietf.org/doc/html/rfc6749#section-4.4

Kind regards
Niklas

**Comment by jimmarino** [comment]
Hi @nikschul that's not it. Looking at this, I don't think we need to link to the OAuth 2 specification. Instead, we should introduce our own terms and definitions section and define it there. @arnoweiss what do you think?

**Comment by arnoweiss** [comment]
Currently, the VPP and CIP define separate "terms" sections which we should consolidate anyway. I think in this case the "relying party" can safely be replaced by "verifier" as defined by the [did spec](https://www.w3.org/TR/vc-data-model/#dfn-verifier) that we link to in the "terms" sections already anyway...
