### ISSUE TITLE
Licence change

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-dcp/decentralized-claims-protocol#61]
The initial contribution was created and transferred under CC-BY-4.0. The [project proposal](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/713) determined that it should be Apache-2.0. We should discuss if this change can simply be done by changing `LICENCE` or if there's a requirement for more ""process"".

**Comment by mspiekermann** [comment]
Just added a triage label. We should add this to our agenda for the next alignment meeting. I see different approaches:
- leave CC-BY 4.0 as there is no compulsion for Apache 2.0 (even we have the statement in the proposal)
- change to Apache 2.0 as we know all contributors and don't expect an issue on their side

In case we decide to go for the Apache license, I volunteer to clarify with EF, if we need a formal process.

**Comment by mspiekermann** [comment]
solved with #80
