### ISSUE TITLE
New DCP context object

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-dcp/decentralized-claims-protocol#63]
Currently, there's still a reference to eclipse-tractusx in the spec's payloads. We should

- [x] create a new context in a namespace tbd.
- [x] publish context incl. referrals
- [x] adjust spec payloads

**Comment by arnoweiss** [comment]
Decision for namespace and naming schema (as per #79):
`https://w3id.org/dspace-dcp/v[version]`

**Comment by wolf4ood** [comment]
@arnoweiss  

going to pick this one, 
i would start by publishing on GH pages the context definition and the JSON-SCHEMA
then i would move to grabbing the w3id for the `dspace-dcp` 

is it ok?

**Comment by arnoweiss** [comment]
thanks, sounds great

**Comment by arnoweiss** [comment]
URI changed to https://w3id.org/dspace-dcp/v0.8. It resolves as intended since https://github.com/perma-id/w3id.org/pull/4539
