### ISSUE TITLE
Add schemas, shapes, samples

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-dcp/decentralized-claims-protocol#64]
To provide implementations with better tooling, the spec should contain json-schemas, shacl-shapes and jsonld-samples. A bit of automation can also ensure that the samples match all requirements.

**Comment by wolf4ood** [comment]
Hi all,

I've worked on a proposal for this in the [repo](https://github.com/wolf4ood/dcp-schema), which I'd like to discuss.

It contains `json-schemas`, the `json-ld` context and examples in json-ld.

The JSON schema and the examples are tested with schema validator and JSON-LD expansion/compaction process
ensuring that they all match the requirements.

**Comment by arnoweiss** [comment]
Thanks for prepping the PR. Will take a closer look tomorrow throughout the day.
