### ISSUE TITLE
CredentialRequestMessage `type` field rename

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-dataspace-dcp/decentralized-claims-protocol#84]
### What's wrong?

In `CredentialRequestMessage` there is a field `type` which expresses the requested credentials. `type` term should be avoided since it might collision with `@type` reserved keyword of JSON-LD.

### Why is this a bug?

A lot of JSON-LD context definitions alias the `type` to `@type` and that would be an issue since the `type` and `@type` will collapse when processing the JSON-LD. 

### How could it be fixed?

Rename `type` to `credentialType`, it will also be aligned with the `CredentialObject`

**Comment by jimmarino** [comment]
Fixed
