### ISSUE TITLE
Incorrect Endpoint mentioned in the Credential Offer Flow example

### ISSUE THREAD

**Issue by nikschul** [eclipse-dataspace-dcp/decentralized-claims-protocol#85]
### What's wrong?

In the specification of the Credential Offer Flow inside the **credential.issuance.protocol.md** the given endpoint `/credentials` does not match the the textual description stating the `/offers` endpoint instead.

### Why is this a bug?

The text mentions a different endpoint than the one used in the example.

### How could it be fixed?

Correct the endpoint in the example to `/offers`.

### More context

<img width="1163" alt="screenshot" src="https://github.com/user-attachments/assets/ec82e0d8-6abb-4fb4-a46e-d4791aac104f">

**Comment by arnoweiss** [comment]
@nikschul - can you check if this is still relevant? I think #102 fixed this by reducing the example to the request body.

https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/#credential-offer-api
