### ISSUE TITLE
JsonWebKey2020 is not really a cryptographic suite but a container for holding (public) key material..

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-dataspace-dcp/decentralized-claims-protocol#94]
JsonWebKey2020 is not really a cryptographic suite but a container for holding (public) key material with support for different crytographic suites. Perhaps not an issue for this PR, but might be a new issue

_Originally posted by @mkollenstart in https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol/pull/89#discussion_r1837884741_

**Comment by paullatzelsperger** [comment]
According to the [spec](https://www.w3.org/TR/vc-jws-2020/) for Linked-Data proofs, it is a _signature_ suite, not a _cryptographic_ suite, and it should be `JsonWebSignature2020`, not `JsonWebKey2020`, so we should put:
```json
"signatureSuites": [
   "JsonWebSignature2022"
]
```
@mkollenstart WDYT?

**Comment by mkollenstart** [comment]
Yes, `JsonWebSignature2020` would be more suitable. The only issue I would see is that this is part of a discontinued draft.
And, as far as I can see, the other way would be to use `DataIntegrityProof`s in the future. But then `cryptosuites` will become relevant again. E.g. `eddsa-rdfc-2022`.

So for now, signatureSuites will be more suitable if we primarily use `JsonWebSignature2020`. But we must be aware of the fact that this might need to change in the future.

**Comment by paullatzelsperger** [comment]
ah good point. so we could just find a generic property name, and be future proof, e.g.:
```json
"cryptography" : [
   "JsonWebSignature202", "eddsa-rdfc-2022", "eddsa-jcs-2022", "..."
]
```

**Comment by mkollenstart** [comment]
Yes, that looks good. And let's monitor whats happening outside
